### ISSUE TITLE
UUID do not define a '.' subpath

### ISSUE THREAD

**Issue by Sansossio** [kamilmysliwiec/nest-cqrs-example#11]
I have downloaded this example, when I try to start the application with npm start I get the following error
```sh
Error: Package exports for ...\node_modules\@nestjs\common\node_modules\uuid' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (...\node_modules\@nestjs\common\decorators\core\injectable.decorator.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) {
````

OS: Windows 10
Node 13.0.1

**Comment by Sansossio** [comment]
I resolved this issue using node 12.7.0
